### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by dinosaw** [GAZ082/MyMovieGallery#3]
Hi there. I'm running Python 3.2 with Python 3 requests installed, however when I try and run main.py, I get the following. Do you have any ideas of what I could be doing wrong?

```
dino@server1:~/scripts/MyMovieGallery$ python3 -V
Python 3.2.3

dino@server1:~/scripts/MyMovieGallery$ which pip3.2
/usr/local/bin/pip3.2

dino@server1:~/scripts/MyMovieGallery$ pip3.2 install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.2/dist-packages

dino@server1:~/scripts/MyMovieGallery$ python3 main.py
Traceback (most recent call last):
  File "/usr/lib/python3.2/json/decoder.py", line 367, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 162, in <module>
    for i in get_movies_from_kodi(host, port):
  File "main.py", line 43, in get_movies_from_kodi
    r = r.json()
  File "/usr/local/lib/python3.2/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 351, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by GAZ082** [comment]
Hi Dino. Thanks for using my script. Looks like the server is throwing and error or something "not JSON"-y
1. Make sure you have enabled the webserver on KODI.
2. Make sure host and port are properly setup based on what port you put in 1 (8080 being the standard) and the host (localhost if running on the same machine than KODI).

Tell me how it goes!

PS: now that i see someone is actually using the script, i'll correct a couple of glitches. :smile:

**Comment by dinosaw** [comment]
I verified that I can connect to Kodi's web interface. I was able to run a few other programs / scripts that exported my library to HTML - I just didn't like them :P 

I'm not sure what else I can try unfortunately

**Comment by GAZ082** [comment]
We have to make it work!
Paste here the configuration part please.

**Comment by GAZ082** [comment]
Closed due inactivity.
